dist: xenial
language: java
jdk:
  - openjdk8
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
script:
  - ./mvnw package
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - JAVA_OPTS: "'-Xms512m -Xmx2g'"